if(EXISTS "/home/runner/work/sdfglib/sdfglib/_codeql_build_dir/tests/sdfglib_test[1]_tests.cmake")
  include("/home/runner/work/sdfglib/sdfglib/_codeql_build_dir/tests/sdfglib_test[1]_tests.cmake")
else()
  add_test(sdfglib_test_NOT_BUILT sdfglib_test_NOT_BUILT)
endif()
