name: LLVM - Unit and Integration Sanitized Tests

on:
  push:
    branches:
      - main
      - llvm-test-suite
  schedule:
    - cron: "0 4 * * *"

jobs:
  llvm-tests-linux-san:
    runs-on:
      group: dahlia
      labels: Linux
    container:
      image: daisytuner/docc-run-env-llvm21-ubuntu-24.04:latest-amd64
    strategy:
      fail-fast: false
      matrix:
        san: ["address", "leak", "undefined"]

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BENCHMARK_TESTS_TOKEN }}
          submodules: recursive

      - name: Mark GitHub Actions workdir as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G Ninja \
            -DCMAKE_C_COMPILER=clang-21 \
            -DCMAKE_CXX_COMPILER=clang++-21 \
            -DCMAKE_BUILD_TYPE=Debug \
            -DSDFG_ENABLE_SANITIZER=ON \
            -DSDFG_SANITIZER=${{ matrix.san }} \
            -DLLVM_BUILD_FRONTEND=ON \
            -DLLVM_BUILD_TESTS=ON \
            -DSDFG_BUILD_TESTS=OFF \
            -DINSTALL_GTEST=OFF \
            -DBUILD_TESTS:BOOL=OFF \
            -DBUILD_BENCHMARKS:BOOL=OFF \
            -DBUILD_BENCHMARKS_GOOGLE:BOOL=OFF \
            ..
          ninja -j$(nproc)
          cpack -G DEB
          apt-get install -y ./docc-llvm*.deb

      - name: Unit Tests
        run: |
          cd build
          ./llvm/tests/docc_llvm_pass_test

      - name: Set up Python
        if: matrix.san == 'leak'
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup virtual environment
        if: matrix.san == 'leak'
        run: |
          python -m venv .venv
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        if: matrix.san == 'leak'
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-xdist lit

      - name: Integration Tests
        # The docc C/C++ compiler currently only works with leak sanitizer
        if: matrix.san == 'leak'
        run: |
          export LLVM_SYMBOLIZER_PATH=$(which llvm-symbolizer-21)

          cd llvm/integration
          pytest -v llvm_test_suite.py
