name: Sanitizer Tests (Address)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  sanitizer-linux-asan:
    runs-on:
      group: dahlia
      labels: openmp
    container:
      image: daisytuner/docc-run-env-llvm21-ubuntu-24.04:latest-amd64

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BENCHMARK_TESTS_TOKEN }}
          submodules: recursive

      - name: Formatting
        shell: bash
        run: |
          shopt -s globstar
          clang-format-19 -style=file --dry-run --Werror sdfg/include/**/*.h sdfg/src/**/*.cpp sdfg/tests/**/*.cpp
          clang-format-19 -style=file --dry-run --Werror opt/include/**/*.h opt/src/**/*.cpp opt/tests/**/*.cpp

      - name: Build
        run: |
          mkdir build
          cd build
          cmake \
            -G Ninja \
            -DCMAKE_C_COMPILER=clang-21 \
            -DCMAKE_CXX_COMPILER=clang++-21 \
            -DCMAKE_BUILD_TYPE=Debug \
            -DSDFG_ENABLE_SANITIZER=ON \
            -DSDFG_SANITIZER=address \
            -DBUILD_TESTS:BOOL=OFF \
            -DBUILD_BENCHMARKS:BOOL=OFF \
            -DBUILD_BENCHMARKS_GOOGLE:BOOL=OFF  \
            ..
          ninja -j$(nproc)

      - name: Unit Tests
        run: |
          cd build/

          ctest --label-exclude "sdfgrpc|sdfgrpc_daisytuner_rpc" --parallel

  sanitizer-macos-asan:
    runs-on:
      group: dahlia
      labels: macOS

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BENCHMARK_TESTS_TOKEN }}
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install ninja cmake
          brew install gmp isl nlohmann-json boost
          brew install libomp

      - name: Build
        run: |
          mkdir build
          cd build
          cmake \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DSDFG_ENABLE_SANITIZER=ON \
            -DSDFG_SANITIZER=address \
            -DBUILD_TESTS:BOOL=OFF \
            -DBUILD_BENCHMARKS:BOOL=OFF \
            -DBUILD_BENCHMARKS_GOOGLE:BOOL=OFF  \
            ..
          ninja

      - name: Unit Tests
        run: |
          cd build/
          ctest --label-exclude "sdfgrpc|sdfgrpc_daisytuner_rpc" --parallel
