name: Unit Tests (macOS)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    - cron: "0 4 * * *"

jobs:
  primary-tests-macos:
    runs-on:
      group: dahlia
      labels: macOS

    env:
      python_version: "3.14"

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BENCHMARK_TESTS_TOKEN }}
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install ninja cmake
          brew install gmp isl nlohmann-json boost
          brew install libomp
          brew install uv

      - name: Set up Python ${{ env.python_version }}
        run: |
          uv python install ${{ env.python_version }}
          uv venv --python ${{ env.python_version }} .venv
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
          echo "PYTHONPATH=$PWD/python" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          uv pip install pybind11 coverage black==25.9.0 build scikit-build-core
          uv pip install pytest pytest-xdist
          uv pip install sympy numpy scipy ml_dtypes jsonschema

      - name: Build
        run: |
          mkdir build
          cd build
          cmake \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DPYTHON_BUILD_FRONTEND=ON \
            -Dpybind11_DIR=$GITHUB_WORKSPACE/.venv/lib/python${{ env.python_version }}/site-packages/pybind11/share/cmake/pybind11 \
            -DBUILD_TESTS:BOOL=OFF \
            -DBUILD_BENCHMARKS:BOOL=OFF \
            -DBUILD_BENCHMARKS_GOOGLE:BOOL=OFF \
            ..
          ninja

      - name: Unit Tests
        run: |
          cd build/

          ctest --label-exclude "sdfgrpc|sdfgrpc_daisytuner_rpc" --parallel

      - name: Python Unit Tests
        env:
          DOCC_ACCESS_TOKEN: ${{ secrets.DOCC_CI_TOKEN }}
        run: |
          export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
          pytest -v -n auto python/tests -m "unmarked"

      - name: Python Integration Tests
        run: |
          export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
          pytest -v -n auto python/benchmarks/

      # - name: Test RTL
      #   run: |
      #     export CPATH=/usr/local/include:$CPATH
      #     export LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH
      #     export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
      #     export PATH=/usr/local/bin:$PATH

      #     pip install pytest pytest-xdist --break-system-packages

      #     cd rtl/tests
      #     pytest -v -s rtl_tests.py
