name: Unit Tests - Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    - cron: "0 4 * * *"

jobs:
  release-linux:
    runs-on:
      group: dahlia
      labels: RTX5060
    container:
      image: daisytuner/docc-run-env-llvm21-ubuntu-24.04:latest-amd64
      options: >-
        --cap-add=PERFMON
        --gpus=all

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BENCHMARK_TESTS_TOKEN }}
          submodules: recursive

      - name: Mark GitHub Actions workdir as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Formatting
        shell: bash
        run: |
          shopt -s globstar
          clang-format-19 -style=file --dry-run --Werror sdfg/include/**/*.h sdfg/src/**/*.cpp sdfg/tests/**/*.cpp
          clang-format-19 -style=file --dry-run --Werror opt/include/**/*.h opt/src/**/*.cpp opt/tests/**/*.cpp

      - name: Build and test
        run: |
          mkdir build
          cd build
          cmake \
            -G Ninja \
            -DCMAKE_C_COMPILER=clang-21 \
            -DCMAKE_CXX_COMPILER=clang++-21 \
            -DCMAKE_INSTALL_PREFIX=/usr/local \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_BUILD_FRONTEND=ON \
            -DLLVM_BUILD_TESTS=ON \
            -DBUILD_TESTS:BOOL=OFF \
            -DBUILD_BENCHMARKS:BOOL=OFF \
            -DBUILD_BENCHMARKS_GOOGLE:BOOL=OFF  \
            ..
          ninja -j$(nproc)
          ninja install

      - name: Unit Tests
        run: |
          cd build/

          ctest --label-exclude "sdfgrpc|sdfgrpc_daisytuner_rpc|capture_io" --parallel

      - name: Test RTL
        run: |
          export CPATH=/usr/local/include:$CPATH
          export LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH
          export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
          export PATH=/usr/local/bin:$PATH

          pip install pytest pytest-xdist --break-system-packages
          pip install jsonschema --break-system-packages

          cd rtl/tests
          pytest -v -s rtl_tests.py

  release-macos:
    runs-on:
      group: dahlia
      labels: macOS

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BENCHMARK_TESTS_TOKEN }}
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install ninja cmake
          brew install gmp isl nlohmann-json boost
          brew install libomp

      - name: Build
        run: |
          mkdir build
          cd build
          cmake \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTS:BOOL=OFF \
            -DBUILD_BENCHMARKS:BOOL=OFF \
            -DBUILD_BENCHMARKS_GOOGLE:BOOL=OFF  \
            ..
          ninja

      - name: Unit Tests
        run: |
          cd build/
          ctest --label-exclude "sdfgrpc|sdfgrpc_daisytuner_rpc|capture_io" --parallel
